<?php

namespace ToolsforeverBundle\Repository;

/**
 * FabriekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FabriekRepository extends \Doctrine\ORM\EntityRepository
{
}
